import type { Metadata } from "next";
import Script from "next/script";
import { Nunito, Geist_Mono } from "next/font/google";
import { Header } from "@/src/features/chat/components/Header";
import Sidebar from "@/src/features/sidebar/components/Sidebar";
import "./globals.css";
import "katex/dist/katex.min.css";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${nunito.variable} ${geistMono.variable} antialiased`}>
        <Script id="theme-init" strategy="beforeInteractive">{`
(function () {
  try {
    var ls = window.localStorage.getItem('theme');
    var m = window.matchMedia('(prefers-color-scheme: dark)');
    var dark = ls ? ls === 'dark' : m.matches;
    var c = document.documentElement.classList;
    dark ? c.add('dark') : c.remove('dark');
  } catch (e) {}
})();`}</Script>
        <div className="flex h-screen bg-background text-foreground">
          <div className="h-full overflow-visible z-10">
            <Sidebar />
          </div>
          <div className="relative flex-1 overflow-hidden flex flex-col">
            <Header />
            <div className="flex-1 min-h-0 overflow-hidden">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
